### PR TITLE
Added new X/twitter icon.

### PR DESCRIPTION
**Pull request by sourabh-vb**

### CODE REVIEW

**Comment by AdamPS** [comment]
Thanks please can you make it match the others?

- viewBox="0 0 28 28"
- The minimised one should have no width, height, style, or blank lines

**Comment by AdamPS** [comment]
Thanks however you need to scale all the co-ordinates also to fit in the new viewbox😃. Hopefully your SVG editing tool can do it automatically. Then also do the second bullet to remove some parts from the minimised one.

**Comment by sourabh-vb** [comment]
@AdamPS Could you please check it now.

**Comment by AdamPS** [comment]
Great, that's better. I think we can safely cut it to 1 (or max 2) decimal places, then I will commit.

**Comment by sourabh-vb** [comment]
Do you want us to change value in decimal inside viewbox or the values in path tag should contains only 1 or 2 decimal digit?

**Comment by AdamPS** [comment]
Values in path tag please.

We can save a few bytes and it should look exactly the same to the eye.

**Comment by sourabh-vb** [comment]
Thanks @AdamPS . Please review it now.

**Comment by AdamPS** [comment]
OK but now missing </path> and again it needs to be just one line please.

I think we don't need `x="0px" y="0px"`

**Comment by sourabh-vb** [comment]
Updated it @AdamPS . Let me know if you need more changes.

**Comment by AdamPS** [comment]
Great thanks.

**Comment by sourabh-vb** [comment]
@AdamPS Apologies! I missed a change in which Both files contains the blankline and End of file so we need to remove that too. So can we create a new fork and create a PR for that?

**Comment by AdamPS** [comment]
OK I just fixed X.min.svg and I also removed some zeros. The other file can have a blank line, it's fine.

**Comment by sourabh-vb** [comment]
Thanks @AdamPS . Really appreciated

**Pull request merged**
